---

- name: Setup common roles on all hosts
  hosts: all
  roles:
  - common
  - apt
  - ntp
  - node_exporter

- name: Setup gateway servers
  hosts: [gw11.regensburg.freifunk.net, gw21.regensburg.freifunk.net, gw31.regensburg.freifunk.net]
  roles:
  - gw-admin-ssh-keys
  - arp-cache
  - batman
  - bird
  - fastd
  - fastd-exporter
  - mesh-interfaces
  - exit-ip
  - dns
  - radvd
  - dhcpd
  - respondd
  - yanic
  - web-gw

- name: Setup confluence server
  hosts: confluence.regensburg.freifunk.net
  roles:
  - confluence

- name: Setup stats server
  hosts: stats.ffrgb
  roles:
  - prometheus
  - grafana
